---
- job:
    name: nova-operator-content-provider
    parent: content-provider-base
    description: |
      This job builds the nova-operator and provides it to child jobs
      It also rebuilds the openstack-operator using the updated nova operator.
    provides:
      - "nova-operator-content"
    vars:
      cifmw_operator_build_org: openstack-k8s-operators
      cifmw_operator_build_operators:
        - name: "openstack-operator"
          src: "~/src/github.com/{{ cifmw_operator_build_org }}/openstack-operator"
          image_base: nova


- job:
    name: nova-operator-base
    description: |
      This is the base job for all nova-operator tests that will deploy
      openstack. the base job does not deploy openstack but it does use
      the nova-operator-content-provider job to provide a registry with
      built operators and installs them on a crc environment. Child jobs
      should take this deployed crc and use the installed operators to
      deploy openstack and then test it. This job will fetch the job
      output directory so child jobs can just add additional logs to that
      in there post-playbooks.
    parent: cifmw-podified-multinode-edpm-base-crc
    abstract: true
    attempts: 1
    dependencies: ["nova-operator-content-provider"]
    required-projects:
      - github.com/openstack-k8s-operators/ci-framework
      - github.com/openstack-k8s-operators/install_yamls
    requires:
      - "nova-operator-content"
    roles:
      - zuul: github.com/openstack-k8s-operators/ci-framework
    pre-run:
      - ci/nova-operator-base/playbooks/pre-wrapper.yaml
    post-run:
      - ci/nova-operator-base/playbooks/collect-logs.yaml

- job:
    name: nova-operator-compute-kit
    parent:  nova-operator-base
    dependencies: ["nova-operator-content-provider"]
    roles:
      - zuul: github.com/openstack-k8s-operators/ci-framework
    description: |
      This job deploy a basic "Compute Starter Kit" topology
      https://www.openstack.org/software/sample-configs#compute-starter-kit
      that is the minium set of openstack services required to boot a vm.
    requires:
      - "nova-operator-content"
    run:
      - ci/nova-operator-compute-kit/playbooks/deploy-openstack.yaml
      - ci/nova-operator-compute-kit/playbooks/tempest.yaml

- job:
    name: nova-operator-kuttl
    parent:  nova-operator-base
    dependencies: ["nova-operator-content-provider"]
    roles:
      - zuul: github.com/openstack-k8s-operators/ci-framework
    description: |
      This job deploy a basic "Compute Starter Kit" topology
      https://www.openstack.org/software/sample-configs#compute-starter-kit
      that is the minium set of openstack services required to boot a vm.
    requires:
      - "nova-operator-content"
    pre-run:
      - ci/nova-operator-kuttl/playbooks/deploy-deps.yaml
    run:
      - ci/nova-operator-kuttl/playbooks/run-kuttl.yaml
    nodeset:
      nodes:
        - name: controller
          label: cloud-centos-9-stream-tripleo-vexxhost
        - name: crc
          label: coreos-crc-extracted-xxl
    vars:
      collection_namespace_override: "nova-kuttl-default"
      zuul_log_collection: true
    extra-vars:
      crc_ci_bootstrap_networking:
        networks:
          default:
            range: 192.168.122.0/24
            mtu: 1500
          internal-api:
            vlan: 20
            range: 172.17.0.0/24
          storage:
            vlan: 21
            range: 172.18.0.0/24
          tenant:
            vlan: 22
            range: 172.19.0.0/24
        instances:
          controller:
            networks:
              default:
                ip: 192.168.122.11
          crc:
            networks:
              default:
                ip: 192.168.122.10
              internal-api:
                ip: 172.17.0.5
              storage:
                ip: 172.18.0.5
              tenant:
                ip: 172.19.0.5
- job:
    name: nova-operator-tempest-multinode
    parent: podified-multinode-edpm-deployment-crc-3comp
    dependencies: ["nova-operator-content-provider"]
    vars:
      cifmw_tempest_tempestconf_profile:
          overrides:
            compute.min_compute_nodes: 3
            compute-feature-enabled.vnc_console: true
            compute-feature-enabled.stable_rescue: true
            compute_feature_enabled.hostname_fqdn_sanitization: true
            validation.run_validation: true
            # NOTE(gibi): This is a WA to force the publicURL as otherwise
            # tempest gets configured with adminURL and that causes test
            # instability.
            identity.v3_endpoint_type: public
      cifmw_tempest_tests_allowed:
        - tempest.
      cifmw_tempest_tests_skipped:
      # TODO(samborka): remove this once we have a running barbican
        - barbican_tempest_plugin.
        - tempest.scenario.test_encrypted_cinder_volumes.TestEncryptedCinderVolumes
      # We don't have a running cinder-volume
        - cinder_tempest_plugin.
        - ServersTestBootFromVolume
        - tempest.api.compute.volumes.test_volumes_list
        - tempest.api.volume.admin
        - tempest.api.volume.test_image_metadata
        - tempest.api.volume.test_snapshot_metadata
        - tempest.api.volume.test_volume_absolute_limits
        - tempest.api.volume.test_volume_metadata
        - tempest.api.volume.test_volumes_actions
        - tempest.api.volume.test_volumes_list
        - tempest.api.volume.test_volumes_negative
        - tempest.api.volume.test_volumes_snapshots
        - tempest.api.volume.test_volumes_snapshots_list
        - tempest.api.compute.admin.test_volume.AttachSCSIVolumeTestJSON
        - tempest.api.compute.admin.test_volumes_negative.VolumesAdminNegativeTest
        - test_delete_server_while_in_attached_volume
        - tempest.api.compute.servers.test_device_tagging
        - test_rebuild_server_with_volume_attached
        - test_rescued_vm_attach_volume
        - test_rescued_vm_detach_volume
        - test_create_server_from_non_bootable_volume
        - test_create_server_invalid_bdm_in_2nd_dict
        - test_attach_volume_shelved_or_offload_server
        - test_detach_volume_shelved_or_offload_server
        - test_attach_detach_volume
        - test_list_get_volume_attachments
        - test_attach_attached_volume
        - test_delete_attached_volume
        - tempest.api.compute.volumes.test_volumes_get
        - tempest.api.volume.admin.test_backends_capabilities
        - tempest.api.volume.admin.test_group_snapshots
        - tempest.api.volume.admin.test_groups
        - tempest.api.volume.admin.test_volume_hosts
        - tempest.api.volume.admin.test_volume_pools
        - tempest.api.volume.admin.test_volume_quotas
        - tempest.api.volume.admin.test_volume_retype
        - tempest.api.volume.admin.test_volume_services.VolumesServicesTestJSON.test_get_service_by_volume_host_name
        - tempest.api.volume.admin.test_volume_type_access
        - tempest.api.volume.admin.test_volume_types.VolumeTypesTest.test_volume_crud_with_volume_type_and_extra_specs
        - tempest.api.volume.admin.test_volumes_actions
        - tempest.api.volume.test_availability_zone
        - tempest.api.volume.test_volume_delete_cascade
        - tempest.api.volume.test_volume_transfers
        - tempest.api.volume.test_volumes_clone
        - tempest.api.volume.test_volumes_extend
        - tempest.api.volume.test_volumes_get
        - tempest.api.volume.test_volumes_snapshots_negative.VolumesSnapshotNegativeTestJSON.test_volume_from_snapshot_decreasing_size
        - test_minimum_basic_instance_hard_reboot_after_vol_snap_deletion
        - tempest.scenario.test_minimum_basic.TestMinimumBasicScenario.test_minimum_basic_scenario
        - test_shelve_volume_backed_instance
        - tempest.scenario.test_stamp_pattern
        - tempest.scenario.test_volume_boot_pattern
        - test_volume_snapshot_create_get_list_delete
        - tempest.api.compute.servers.test_server_rescue.ServerBootFromVolumeStableRescueTest
        - test_stable_device_rescue_disk_virtio_with_volume_attached
        - test_resize_volume_backed_server_confirm
        - test_resize_server_revert_with_volume_attached
      # Need to check
        - tempest.api.compute.admin.test_auto_allocate_network.AutoAllocateNetworkTest.test_server_multi_create_auto_allocate
        - tempest.api.object_storage.test_container_sync_middleware
        - tempest.api.object_storage.test_object_version
        - tempest.api.compute.servers.test_server_rescue.ServerStableDeviceRescueTestIDE
        - tempest.api.network.admin.test_dhcp_agent_scheduler
      # Migration does not work yet
        - tempest.api.compute.admin.test_live_migration
        - test_server_connectivity_live_migration
      # Swift test failing with unauthorized errors
        - tempest.api.object_storage
        - tempest.scenario.test_object_storage
- project:
    name: openstack-k8s-operators/nova-operator
    github-check:
      jobs:
        - nova-operator-content-provider
        - nova-operator-kuttl
        - nova-operator-tempest-multinode
